### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kaklik** [drogenlied/pypid#1]
Hello, 
I do not understand how this code would work.  Where is an example of real system regulation?  I only see two files in example directory one is a pid_repsonse.py which analyses the system parameters and the second is a temp_monitor.py which record system temperature every 10 seconds. 

None example controls a real system.

**Comment by drogenlied** [comment]
Please do not use this.
From the description at  http://blog.tremily.us/posts/pypid/ I thought this was going to be useful code and started fixing it up for use with python 3 but it is completely broken and most likely never worked.
